import Database from '@/components/database';
import './globals.css'
import ThemeRegistry from '@/components/themeregistry';

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <head>
        <link rel="preconnect" href="https://fonts.googleapis.com" />
        <link rel="preconnect" href="https://fonts.gstatic.com" crossOrigin='anonymous' />
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Roboto:wght@300;400;500;600;700&display=swap"
        />  
      </head>    

      <body className='bg'>
        <ThemeRegistry>
          <Database>
            {children}
          </Database>
        </ThemeRegistry>
      </body>
    </html>
  )
}
